name: Ingenious Geeks
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50211
logo: null
title: Ingenious Geeks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f900'
    - '#00d7e9'
    - '#5fe900'
    - '#337200'
    - '#020001'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
