name: Ingenious Geeks
favicon: null
layout_spectrum: 0.75677
typography_spectrum: 0.50211
logo: null
title: Ingenious Geeks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#fe00fa'
    - '#0194a6'
    - '#01fafd'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
