name: Ingenious Geeks
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50211
logo: null
title: Ingenious Geeks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a45991'
    - '#570f51'
    - '#3db1e2'
    - '#ffb18a'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
