name: ingeniousgeeks
favicon: null
layout_spectrum: 0.14222829788923264
typography_spectrum: 0.34571305313147604
logo: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3e8e9'
    - '#5c7a8a'
    - '#365a70'
    - '#15a8dc'
    - '#62c1e4'
  brandStrength: 0.07638442469760776
  lightness: 0.05053491215221584
  saturation: 0.9299788239877671
  rhythmicContrast: 0.5067192430142313
purpose: []
